# Generated by Django 2.1.7 on 2019-02-19 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costs',
            new_name='Cost',
        ),
        migrations.RenameModel(
            old_name='Operations',
            new_name='Operation',
        ),
    ]
