# Generated by Django 2.1.7 on 2019-02-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20190219_0354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='category',
            new_name='companyCode',
        ),
        migrations.AddField(
            model_name='plant',
            name='conversion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
