# Generated by Django 2.1.7 on 2019-02-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20190219_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='conversion',
            field=models.FloatField(),
        ),
    ]
