# Generated by Django 2.1.7 on 2019-02-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20190219_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='OBDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=3)),
                ('plant', models.CharField(max_length=5)),
                ('costCounter', models.IntegerField()),
                ('period', models.IntegerField()),
                ('value', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('variance', models.IntegerField(default=0)),
            ],
        ),
    ]
