# Generated by Django 2.1.7 on 2019-02-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20190219_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obdb',
            old_name='costCenter',
            new_name='costCentre',
        ),
    ]
