# Generated by Django 2.1.7 on 2019-02-19 17:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_auto_20190219_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consolidated_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('value', models.FloatField()),
                ('actual', models.BooleanField(default=False)),
                ('variance', models.IntegerField(default=0)),
                ('cost_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Cost')),
                ('operation_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Operation')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Plant')),
            ],
        ),
        migrations.DeleteModel(
            name='OBDB',
        ),
    ]
