# Generated by Django 2.1.7 on 2019-02-19 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_auto_20190219_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='costCenter',
            new_name='cost_center',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='operationType',
            new_name='operation_type',
        ),
    ]
